# [llm_global]
# type - "local" or "openai"
# model_path - specify path to gguf file when type is "local"
# verbose - boolean, whether to write verbose logs
# ... params to be obtained by the LLM



[llm_global]
type = "openai"

# TODO custiomisations per stage